// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-otwc2X0JZVy32gajeMk1VA7ZZKe428w',
    appId: '1:662836698252:web:9bec8640b2d3252f436fa9',
    messagingSenderId: '662836698252',
    projectId: 'teammanager-1e970',
    authDomain: 'teammanager-1e970.firebaseapp.com',
    storageBucket: 'teammanager-1e970.firebasestorage.app',
    measurementId: 'G-CDK6DB0GM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxLiXa1HMsaDVSVuw1xHhNA2GAiW6pXsk',
    appId: '1:662836698252:android:f5f3810a4dd90567436fa9',
    messagingSenderId: '662836698252',
    projectId: 'teammanager-1e970',
    storageBucket: 'teammanager-1e970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDda47B6gdnI_1TSs3SIRofGLYTByU4Ows',
    appId: '1:662836698252:ios:89bffb6a298340aa436fa9',
    messagingSenderId: '662836698252',
    projectId: 'teammanager-1e970',
    storageBucket: 'teammanager-1e970.firebasestorage.app',
    iosBundleId: 'com.example.doAn',
  );
}
